export const ActionTypes = {
    SET_BOOKS : "SET_BOOKS",
    SELECTED_BOOKS : "SELECTED_BOOKS",
    REMOVE_SELECTED_BOOK: "REMOVE_SELECTED_BOOK",
    UPDATE_SELECTED_BOOK: "UPDATE_SELECTED_BOOK",
    CREATE_BOOK: "CREATE_BOOK",
}